DROP TABLE IF EXISTS kibun_memo;

CREATE TABLE IF NOT EXISTS kibun_memo (
	id INT NOT NULL AUTO_INCREMENT,
	feeling VARCHAR(100) NOT NULL,
	text VARCHAR(100) NOT NULL,
	day DATE NOT NULL,
	PRIMARY KEY(id)
);

DROP TABLE IF EXISTS login_user;

CREATE TABLE IF NOT EXISTS login_user(
  id INT NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);