DROP TABLE IF EXISTS kibun_memo;

CREATE TABLE IF NOT EXISTS kibun_memo (
	id INT NOT NULL AUTO_INCREMENT,
	feeling VARCHAR(100) NOT NULL,
	text VARCHAR(100) NOT NULL,
	day DATE NOT NULL,
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS loginUser(
  userId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(128) NOT NULL
);